Documentation:
  Enabled: false
Rails:
  Enabled: true
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
    - '/config.ru'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 30
