Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
    - '/config.ru'
    - 'Gemfile'
    - 'app/inputs/*'
