Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
